version: '3.8'
services:
  postgres:
    image: postgres:15-alpine
    container_name: dungeon_crawler_db
    environment:
      POSTGRES_DB: dungeon_crawler
      POSTGRES_USER: aviral
      POSTGRES_PASSWORD: password
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U aviral -d dungeon_crawler"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: dungeon_crawler_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data: